import type { SxProps, Theme } from '@mui/material';
import { alpha } from '@mui/material/styles';

export const libraryPageStyles = (theme: Theme): Record<string, SxProps<Theme>> => {
  const fp = theme.palette.foundation;
  return {
    root: {
      flex: 1,
      minHeight: 0,
      display: 'flex',
      backgroundColor: 'transparent',
      overflow: 'hidden',
    },
    workspace: {
      flex: 1,
      minWidth: 0,
      minHeight: 0,
      display: 'grid',
      gridTemplateColumns: { xs: '1fr', md: '340px minmax(0, 1fr)', lg: '380px minmax(0, 1fr)' },
      gap: 2,
      p: { xs: 1.5, md: 2 },
      overflow: 'hidden',
    },
    libraryColumn: {
      position: 'relative',
      minWidth: 0,
      minHeight: 0,
      borderRadius: 2,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.surface,
      overflow: 'hidden',
      display: 'flex',
      flexDirection: 'column',
    },
    dropOverlay: {
      position: 'absolute',
      inset: 0,
      zIndex: 5,
      display: 'flex',
      flexDirection: 'column',
      gap: 1.25,
      alignItems: 'center',
      justifyContent: 'center',
      textAlign: 'center',
      px: 3,
      pointerEvents: 'none',
      borderRadius: 2,
      border: `2px dashed ${fp.accent}`,
      backgroundColor: alpha(fp.accent, 0.12),
      backdropFilter: 'blur(2px)',
      color: fp.accent,
    },
    dropOverlayTitle: {
      fontSize: 18,
      fontWeight: 850,
      color: fp.text.primary,
    },
    dropOverlayText: {
      fontSize: 13,
      color: fp.text.muted,
      maxWidth: 280,
    },
    detailColumn: {
      minWidth: 0,
      minHeight: 0,
      display: 'flex',
      flexDirection: 'column',
      gap: 1.5,
      overflow: 'hidden',
    },
    brandBlock: {
      p: 2.25,
      borderBottom: `1px solid ${fp.divider}`,
      background: `linear-gradient(135deg, ${fp.bg.surface} 0%, ${fp.bg.elevated} 100%)`,
      flexShrink: 0,
    },
    brandHeaderRow: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 1.5,
    },
    brandTitleBlock: {
      minWidth: 0,
    },
    playlistToggle: {
      width: 44,
      height: 44,
      borderRadius: 1,
      border: `2px solid ${fp.status.danger}`,
      color: fp.status.danger,
      backgroundColor: fp.bg.surface,
      flexShrink: 0,
      '&:hover': {
        backgroundColor: fp.bg.hover,
      },
    },
    playlistToggleActive: {
      width: 44,
      height: 44,
      borderRadius: 1,
      border: `2px solid ${fp.accent}`,
      color: fp.accent,
      backgroundColor: fp.bg.elevated,
      flexShrink: 0,
      '&:hover': {
        backgroundColor: fp.bg.hover,
      },
    },
    eyebrow: {
      fontSize: 11,
      fontWeight: 800,
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      color: fp.accent,
      mb: 0.5,
    },
    title: {
      m: 0,
      fontSize: { xs: 24, md: 28 },
      lineHeight: 1.08,
      color: fp.text.primary,
      fontWeight: 850,
    },
    libraryTools: {
      p: 1.25,
      borderBottom: `1px solid ${fp.divider}`,
      display: 'flex',
      flexDirection: 'column',
      gap: 1,
      flexShrink: 0,
    },
    searchField: {
      width: '100%',
      '& .MuiInputBase-root': {
        gap: 1,
      },
    },
    toolButtons: {
      display: 'grid',
      gridTemplateColumns: { xs: '1fr', sm: 'repeat(3, minmax(0, 1fr))' },
      gap: 0.75,
      '& .MuiButton-root': {
        minWidth: 0,
        minHeight: 0,
        height: 44,
        px: 1,
        py: 0,
        fontSize: 13,
        lineHeight: 1,
        whiteSpace: 'nowrap',
      },
      '& .MuiButton-startIcon': {
        mr: 0.55,
      },
      '& .MuiSvgIcon-root': {
        fontSize: 18,
      },
    },
    listHeader: {
      px: 1.5,
      py: 1.25,
      borderBottom: `1px solid ${fp.divider}`,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 1.5,
      flexShrink: 0,
    },
    panelTitle: {
      fontSize: 14,
      fontWeight: 850,
      color: fp.text.primary,
    },
    panelSubtle: {
      mt: 0.3,
      fontSize: 12,
      color: fp.text.muted,
    },
    listHeaderActions: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      flexWrap: 'wrap',
      gap: 0.75,
      minWidth: 0,
    },
    sortSelect: {
      minWidth: 128,
      maxWidth: 170,
      backgroundColor: fp.bg.surface,
      '& .MuiSelect-select': {
        py: 0.65,
        fontSize: 12,
        color: fp.text.primary,
      },
    },
    pill: {
      px: 0.85,
      py: 0.3,
      borderRadius: 1,
      backgroundColor: fp.bg.elevated,
      border: `1px solid ${fp.divider}`,
      color: fp.text.secondary,
      fontSize: 12,
      lineHeight: 1.2,
      whiteSpace: 'nowrap',
    },
    trackList: {
      minHeight: 0,
      overflowY: 'auto',
      display: 'flex',
      flexDirection: 'column',
      gap: 0.75,
      p: 1,
    },
    trackItem: {
      width: '100%',
      textAlign: 'left',
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.content,
      color: fp.text.primary,
      borderRadius: 1.5,
      p: 1,
      cursor: 'pointer',
      display: 'grid',
      gridTemplateColumns: '38px minmax(0, 1fr)',
      gridTemplateRows: 'auto auto',
      gap: 0.75,
      alignItems: 'center',
      transition: 'border-color 140ms ease, background-color 140ms ease, transform 140ms ease',
      '&:hover': {
        borderColor: fp.accent,
        backgroundColor: fp.bg.hover,
        transform: 'translateY(-1px)',
      },
    },
    trackItemActive: {
      borderColor: fp.accent,
      backgroundColor: fp.bg.elevated,
    },
    trackItemSelected: {
      borderColor: fp.status.success,
      backgroundColor: fp.bg.elevated,
    },
    batchToolbar: {
      mx: 1,
      my: 1,
      p: 1,
      borderRadius: 1.5,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.elevated,
      display: 'flex',
      alignItems: { xs: 'stretch', sm: 'center' },
      justifyContent: 'space-between',
      gap: 1,
      flexDirection: { xs: 'column', sm: 'row' },
      flexShrink: 0,
    },
    batchInfo: {
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column',
      flexWrap: 'nowrap',
      whiteSpace: 'nowrap',
    },
    batchTitle: {
      fontSize: 13,
      fontWeight: 850,
      color: fp.text.primary,
      whiteSpace: 'nowrap',
    },
    batchActions: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: 0.75,
      justifyContent: { xs: 'stretch', sm: 'flex-end' },
      '& .MuiButton-root': {
        minWidth: 0,
      },
    },
    dangerButton: {
      backgroundColor: fp.status.danger,
      color: fp.bg.surface,
      '&:hover': {
        backgroundColor: fp.status.danger,
      },
      '&:disabled': {
        backgroundColor: fp.bg.hover,
        color: fp.text.muted,
      },
    },
    trackIndex: {
      width: 32,
      height: 32,
      borderRadius: 1,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.surface,
      color: fp.text.muted,
      fontSize: 12,
      fontWeight: 800,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gridRow: '1 / 3',
      '& .MuiCheckbox-root': {
        p: 0,
        color: fp.text.muted,
      },
      '& .MuiCheckbox-root.Mui-checked': {
        color: fp.status.success,
      },
    },
    trackMain: {
      minWidth: 0,
    },
    trackTitle: {
      fontSize: 13,
      fontWeight: 850,
      color: fp.text.primary,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      mb: 0.45,
    },
    trackMeta: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: 0.55,
      alignItems: 'center',
      color: fp.text.muted,
      fontSize: 11,
      lineHeight: 1.35,
    },
    trackAside: {
      gridColumn: '2',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 0.75,
    },
    trackItemActions: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 0.25,
      '& .MuiIconButton-root': {
        width: 28,
        height: 28,
        borderRadius: 1,
        color: fp.text.secondary,
      },
      '& .MuiIconButton-root:hover': {
        color: fp.accent,
        backgroundColor: fp.bg.hover,
      },
    },
    trackActionTooltipTarget: {
      display: 'inline-flex',
    },
    trackRatio: {
      color: fp.text.secondary,
      fontSize: 12,
      fontWeight: 850,
      textAlign: 'left',
    },
    detailHero: {
      borderRadius: 2,
      border: `1px solid ${fp.divider}`,
      background: `linear-gradient(145deg, ${fp.bg.surface} 0%, ${fp.bg.elevated} 100%)`,
      p: 2.25,
      display: 'grid',
      gridTemplateColumns: { xs: '1fr', lg: 'minmax(0, 1fr) auto' },
      alignItems: 'center',
      gap: 2,
      flexShrink: 0,
    },
    detailTitleBlock: {
      minWidth: 0,
    },
    detailTitle: {
      m: 0,
      fontSize: { xs: 24, md: 30 },
      lineHeight: 1.1,
      color: fp.text.primary,
      fontWeight: 850,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: { xs: 'normal', lg: 'nowrap' },
    },
    detailMeta: {
      mt: 0.75,
      color: fp.text.secondary,
      fontSize: 13,
      lineHeight: 1.55,
    },
    detailEmptyHero: {
      minWidth: 0,
    },
    quickStats: {
      display: 'grid',
      gridTemplateColumns: { xs: 'repeat(2, minmax(0, 1fr))', sm: 'repeat(4, minmax(0, 1fr))', lg: 'repeat(4, 104px)' },
      gap: 0.75,
    },
    statChip: {
      p: 1,
      borderRadius: 1.5,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.surface,
      display: 'flex',
      gap: 0.75,
      alignItems: 'center',
      color: fp.text.secondary,
      minWidth: 0,
    },
    statValue: {
      fontSize: 15,
      fontWeight: 850,
      color: fp.text.primary,
      lineHeight: 1.1,
      fontVariantNumeric: 'tabular-nums',
    },
    statLabel: {
      mt: 0.2,
      fontSize: 10,
      color: fp.text.muted,
      whiteSpace: 'nowrap',
    },
    panelTabs: {
      display: 'grid',
      gridTemplateColumns: { xs: '1fr 1fr', lg: 'repeat(4, minmax(0, 1fr))' },
      gap: 1,
      flexShrink: 0,
    },
    panelTab: {
      textAlign: 'left',
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.surface,
      color: fp.text.secondary,
      borderRadius: 1.5,
      p: 1.25,
      cursor: 'pointer',
      transition: 'border-color 140ms ease, background-color 140ms ease',
      '&:hover:not(:disabled)': {
        borderColor: fp.accent,
        backgroundColor: fp.bg.hover,
      },
      '&:disabled': {
        cursor: 'not-allowed',
        opacity: 0.55,
      },
    },
    panelTabActive: {
      textAlign: 'left',
      border: `1px solid ${fp.accent}`,
      backgroundColor: fp.bg.elevated,
      color: fp.text.primary,
      borderRadius: 1.5,
      p: 1.25,
      cursor: 'pointer',
    },
    panelTabLabel: {
      fontSize: 13,
      fontWeight: 850,
      color: 'inherit',
      mb: 0.3,
    },
    panelTabDesc: {
      fontSize: 11,
      color: fp.text.muted,
      lineHeight: 1.45,
    },
    panelBody: {
      minHeight: 0,
      overflowY: 'auto',
      borderRadius: 2,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.surface,
      p: 1.5,
    },
    panelStack: {
      display: 'flex',
      flexDirection: 'column',
      gap: 1.5,
    },
    playlistPanel: {
      minHeight: 0,
      display: 'flex',
      flexDirection: 'column',
      gap: 1.5,
      overflow: 'hidden',
    },
    playlistHero: {
      borderRadius: 2,
      border: `1px solid ${fp.divider}`,
      background: `linear-gradient(145deg, ${fp.bg.surface} 0%, ${fp.bg.elevated} 100%)`,
      p: 2.25,
      display: 'grid',
      gridTemplateColumns: { xs: '1fr', lg: 'minmax(0, 1fr) auto' },
      alignItems: 'center',
      gap: 2,
      flexShrink: 0,
    },
    playlistHeroText: {
      minWidth: 0,
    },
    playlistHeroActions: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: { xs: 'stretch', lg: 'flex-end' },
      flexWrap: 'wrap',
      gap: 0.75,
      '& .MuiButton-root': {
        minWidth: 0,
      },
    },
    playlistToolbar: {
      borderRadius: 1.5,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.surface,
      p: 1,
      display: 'flex',
      alignItems: { xs: 'stretch', md: 'center' },
      justifyContent: 'space-between',
      flexDirection: { xs: 'column', md: 'row' },
      gap: 1,
      flexShrink: 0,
    },
    playlistModeGroup: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: 0.75,
    },
    playlistMode: {
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.content,
      color: fp.text.secondary,
      borderRadius: 1,
      px: 1,
      py: 0.65,
      fontSize: 12,
      fontWeight: 750,
      display: 'inline-flex',
      alignItems: 'center',
      gap: 0.55,
      cursor: 'pointer',
      transition: 'border-color 140ms ease, background-color 140ms ease',
      '&:hover': {
        borderColor: fp.accent,
        backgroundColor: fp.bg.hover,
      },
    },
    playlistModeActive: {
      border: `1px solid ${fp.accent}`,
      backgroundColor: fp.bg.elevated,
      color: fp.text.primary,
      borderRadius: 1,
      px: 1,
      py: 0.65,
      fontSize: 12,
      fontWeight: 850,
      display: 'inline-flex',
      alignItems: 'center',
      gap: 0.55,
      cursor: 'pointer',
    },
    playlistList: {
      minHeight: 0,
      overflowY: 'auto',
      display: 'flex',
      flexDirection: 'column',
      gap: 0.75,
      p: 1,
      borderRadius: 2,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.surface,
    },
    playlistRow: {
      width: '100%',
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.content,
      color: fp.text.primary,
      borderRadius: 1.5,
      p: 1,
      display: 'grid',
      gridTemplateColumns: { xs: '28px 38px minmax(0, 1fr)', md: '28px 38px minmax(0, 1fr) auto' },
      gap: 0.75,
      alignItems: 'center',
      cursor: 'pointer',
      transition: 'border-color 140ms ease, background-color 140ms ease, opacity 140ms ease',
      '&:hover': {
        borderColor: fp.accent,
        backgroundColor: fp.bg.hover,
      },
    },
    playlistRowActive: {
      borderColor: fp.accent,
      backgroundColor: fp.bg.elevated,
    },
    playlistRowDragging: {
      opacity: 0.58,
      borderColor: fp.status.success,
    },
    playlistDragHandle: {
      color: fp.text.muted,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'grab',
    },
    playlistIndex: {
      width: 32,
      height: 32,
      borderRadius: 1,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.surface,
      color: fp.text.muted,
      fontSize: 12,
      fontWeight: 800,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    playlistRowMain: {
      minWidth: 0,
    },
    playlistRowActions: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 0.75,
      gridColumn: { xs: '3 / 4', md: 'auto' },
      flexWrap: 'wrap',
      '& .MuiButton-root': {
        minWidth: 82,
      },
    },
    playlistEmpty: {
      minHeight: 240,
      display: 'flex',
      flexDirection: 'column',
      gap: 1,
      alignItems: 'center',
      justifyContent: 'center',
      textAlign: 'center',
      color: fp.text.muted,
      px: 4,
      borderRadius: 2,
      border: `1px dashed ${fp.divider}`,
      backgroundColor: fp.bg.surface,
    },
    panelHeaderCard: {
      p: 2,
      borderRadius: 1.5,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.content,
      display: 'flex',
      alignItems: { xs: 'stretch', md: 'center' },
      justifyContent: 'space-between',
      gap: 2,
      flexDirection: { xs: 'column', md: 'row' },
    },
    sectionEyebrow: {
      fontSize: 11,
      fontWeight: 800,
      letterSpacing: 1,
      textTransform: 'uppercase',
      color: fp.accent,
      mb: 0.45,
    },
    sectionBigTitle: {
      fontSize: 18,
      fontWeight: 850,
      color: fp.text.primary,
      mb: 0.35,
    },
    sectionDesc: {
      fontSize: 12,
      color: fp.text.secondary,
      lineHeight: 1.55,
    },
    settingsGrid: {
      display: 'grid',
      gridTemplateColumns: { xs: '1fr', lg: 'minmax(0, 1fr) 280px' },
      gap: 1.5,
      alignItems: 'start',
    },
    settingsMain: {
      display: 'flex',
      flexDirection: 'column',
      gap: 1.25,
      minWidth: 0,
    },
    settingsAside: {
      display: 'flex',
      flexDirection: 'column',
      gap: 1.25,
      minWidth: 0,
      position: { lg: 'sticky' },
      top: { lg: 0 },
    },
    section: {
      p: 1.5,
      borderRadius: 1.5,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.content,
      display: 'flex',
      flexDirection: 'column',
      gap: 1.15,
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: 850,
      color: fp.text.primary,
    },
    sectionHeadingRow: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 1,
      color: fp.text.secondary,
    },
    formGrid: {
      display: 'grid',
      gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))' },
      gap: 1,
    },
    trackActions: {
      display: 'flex',
      gap: 0.75,
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
    },
    trackToggleGrid: {
      display: 'grid',
      gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))', lg: 'repeat(3, minmax(0, 1fr))' },
      gap: 0.75,
    },
    trackToggle: {
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.surface,
      color: fp.text.secondary,
      borderRadius: 1.25,
      px: 0.8,
      py: 0.45,
      display: 'flex',
      alignItems: 'center',
      gap: 0.35,
      cursor: 'pointer',
      fontSize: 12,
      transition: 'border-color 140ms ease, background-color 140ms ease',
      '&:hover': {
        borderColor: fp.accent,
        backgroundColor: fp.bg.hover,
      },
    },
    trackToggleActive: {
      border: `1px solid ${fp.accent}`,
      backgroundColor: fp.bg.elevated,
      color: fp.text.primary,
      borderRadius: 1.25,
      px: 0.8,
      py: 0.45,
      display: 'flex',
      alignItems: 'center',
      gap: 0.35,
      cursor: 'pointer',
      fontSize: 12,
      transition: 'border-color 140ms ease, background-color 140ms ease',
    },
    field: {
      display: 'flex',
      flexDirection: 'column',
      gap: 0.6,
    },
    fieldLabel: {
      fontSize: 11,
      color: fp.text.muted,
      textTransform: 'uppercase',
      letterSpacing: 0.7,
      fontWeight: 750,
    },
    fieldHelper: {
      fontSize: 11,
      color: fp.text.muted,
      lineHeight: 1.45,
    },
    miniMetric: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 1,
      py: 0.55,
      borderBottom: `1px solid ${fp.divider}`,
      '&:last-of-type': {
        borderBottom: 0,
      },
    },
    miniMetricLabel: {
      fontSize: 12,
      color: fp.text.secondary,
    },
    miniMetricValue: {
      fontSize: 13,
      fontWeight: 850,
      color: fp.text.primary,
    },
    settingsActions: {
      display: 'grid',
      gridTemplateColumns: '1fr',
      gap: 1,
    },
    emptyList: {
      minHeight: 220,
      display: 'flex',
      flexDirection: 'column',
      gap: 1,
      alignItems: 'center',
      justifyContent: 'center',
      textAlign: 'center',
      color: fp.text.muted,
      px: 3,
      flex: 1,
    },
    emptyDetail: {
      flex: 1,
      minHeight: 0,
      borderRadius: 2,
      border: `1px dashed ${fp.divider}`,
      backgroundColor: fp.bg.surface,
      display: 'flex',
      flexDirection: 'column',
      gap: 1,
      alignItems: 'center',
      justifyContent: 'center',
      textAlign: 'center',
      color: fp.text.muted,
      px: 4,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: 850,
      color: fp.text.primary,
    },
    emptyText: {
      maxWidth: 460,
      fontSize: 13,
      lineHeight: 1.65,
      color: fp.text.secondary,
    },
    error: {
      p: 1.2,
      borderRadius: 1.5,
      backgroundColor: fp.bg.elevated,
      color: fp.status.danger,
      fontSize: 13,
      border: `1px solid ${fp.status.danger}`,
    },
    hint: {
      p: 1.2,
      borderRadius: 1.5,
      backgroundColor: fp.bg.elevated,
      color: fp.text.secondary,
      fontSize: 12,
      border: `1px solid ${fp.divider}`,
    },
  };
};
