import type { SxProps, Theme } from '@mui/material';

export const editorPageStyles = (theme: Theme): Record<string, SxProps<Theme>> => {
  const fp = theme.palette.foundation;
  return {
    root: {
      flex: 1,
      minHeight: 0,
      display: 'flex',
      backgroundColor: fp.bg.content,
      overflow: 'hidden',
    },
    body: {
      flex: 1,
      minHeight: 0,
      overflowY: 'auto',
      p: 4,
      display: 'grid',
      gridTemplateColumns: { xs: '1fr', lg: 'minmax(360px, 0.92fr) minmax(520px, 1.08fr)' },
      gap: 3,
      alignItems: 'start',
    },
    hero: {
      gridColumn: '1 / -1',
      p: 4,
      borderRadius: 2,
      border: `1px solid ${fp.divider}`,
      background: `linear-gradient(135deg, ${fp.bg.surface} 0%, ${fp.bg.elevated} 100%)`,
      display: 'flex',
      justifyContent: 'space-between',
      gap: 3,
      alignItems: { xs: 'stretch', md: 'center' },
      flexDirection: { xs: 'column', md: 'row' },
    },
    eyebrow: {
      fontSize: 12,
      fontWeight: 700,
      letterSpacing: 1.4,
      textTransform: 'uppercase',
      color: fp.accent,
      mb: 1,
    },
    title: {
      m: 0,
      fontSize: { xs: 28, md: 36 },
      lineHeight: 1.1,
      color: fp.text.primary,
      fontWeight: 800,
    },
    subtitle: {
      mt: 1.5,
      maxWidth: 760,
      color: fp.text.secondary,
      fontSize: 14,
      lineHeight: 1.7,
    },
    actions: {
      display: 'flex',
      gap: 1.25,
      flexWrap: 'wrap',
      justifyContent: { xs: 'flex-start', md: 'flex-end' },
    },
    panel: {
      minHeight: 360,
      borderRadius: 2,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.surface,
      overflow: 'hidden',
    },
    panelHeader: {
      px: 2.5,
      py: 2,
      borderBottom: `1px solid ${fp.divider}`,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 2,
    },
    panelTitle: {
      fontSize: 14,
      fontWeight: 700,
      color: fp.text.primary,
    },
    pill: {
      px: 1,
      py: 0.35,
      borderRadius: 1,
      backgroundColor: fp.bg.elevated,
      border: `1px solid ${fp.divider}`,
      color: fp.text.secondary,
      fontSize: 12,
      lineHeight: 1.2,
    },
    content: {
      p: 2.5,
      display: 'flex',
      flexDirection: 'column',
      gap: 2,
    },
    empty: {
      minHeight: 240,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      textAlign: 'center',
      color: fp.text.muted,
      px: 4,
    },
    section: {
      p: 2,
      borderRadius: 1.5,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.content,
      display: 'flex',
      flexDirection: 'column',
      gap: 1.5,
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: 700,
      color: fp.text.primary,
    },
    profileRow: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: 1,
    },
    profileChip: {
      borderRadius: 1,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.elevated,
      color: fp.text.secondary,
      px: 1.25,
      py: 0.6,
      fontSize: 12,
      cursor: 'pointer',
      '&[data-active="true"]': {
        borderColor: fp.accent,
        color: fp.text.primary,
      },
    },
    fieldGrid: {
      display: 'grid',
      gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))' },
      gap: 1.5,
    },
    field: {
      display: 'flex',
      flexDirection: 'column',
      gap: 0.75,
    },
    fieldLabel: {
      fontSize: 12,
      color: fp.text.muted,
      textTransform: 'uppercase',
      letterSpacing: 0.7,
    },
    fieldValue: {
      color: fp.text.primary,
      fontSize: 14,
      fontWeight: 700,
    },
    helper: {
      fontSize: 12,
      color: fp.text.muted,
    },
    error: {
      p: 1.5,
      borderRadius: 1.5,
      backgroundColor: fp.bg.elevated,
      color: fp.status.danger,
      fontSize: 13,
      border: `1px solid ${fp.status.danger}`,
    },
    hint: {
      p: 1.5,
      borderRadius: 1.5,
      backgroundColor: fp.bg.elevated,
      color: fp.status.warning,
      fontSize: 13,
      border: `1px solid ${fp.status.warning}`,
    },
    footer: {
      display: 'flex',
      justifyContent: 'space-between',
      gap: 2,
      flexWrap: 'wrap',
      pt: 1,
    },
    summaryGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      gap: 1.25,
    },
    summaryCard: {
      p: 1.5,
      borderRadius: 1.5,
      backgroundColor: fp.bg.content,
      border: `1px solid ${fp.divider}`,
    },
    summaryLabel: {
      fontSize: 11,
      color: fp.text.muted,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      mb: 0.75,
    },
    summaryValue: {
      color: fp.text.primary,
      fontSize: 18,
      fontWeight: 800,
    },
  };
};
