import type { SxProps, Theme } from '@mui/material';

export const macroPageStyles = (theme: Theme): Record<string, SxProps<Theme>> => {
  const fp = theme.palette.foundation;
  return {
    page: {
      flex: 1,
      minHeight: 0,
      minWidth: 0,
      display: 'flex',
      flexDirection: 'column',
      gap: 2,
      p: { xs: 1.5, md: 2 },
      overflow: 'hidden',
    },
    pageHeader: {
      display: 'flex',
      flexDirection: 'column',
      gap: 0.5,
      flexShrink: 0,
    },
    pageEyebrow: {
      fontSize: 12,
      fontWeight: 700,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      color: fp.text.muted,
    },
    pageTitle: {
      fontSize: 24,
      fontWeight: 800,
      color: fp.text.primary,
    },
    pageHint: {
      fontSize: 13,
      color: fp.text.secondary,
      maxWidth: 720,
      lineHeight: 1.6,
    },
    root: {
      flex: 1,
      minHeight: 0,
      display: 'grid',
      gridTemplateColumns: '210px minmax(280px, 1fr) 260px',
      gap: 1.5,
      alignItems: 'stretch',
      overflow: 'hidden',
    },
    panel: {
      border: `1px solid ${fp.divider}`,
      borderRadius: 1.5,
      backgroundColor: fp.bg.surface,
      overflow: 'hidden',
      display: 'flex',
      flexDirection: 'column',
      minHeight: 0,
    },
    panelHeader: {
      px: 1.5,
      py: 1.25,
      borderBottom: `1px solid ${fp.divider}`,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 1,
      flexShrink: 0,
    },
    panelTitle: {
      fontSize: 13,
      fontWeight: 700,
      color: fp.text.primary,
    },
    list: {
      display: 'flex',
      flexDirection: 'column',
      p: 1,
      gap: 0.75,
      minHeight: 0,
      overflowY: 'auto',
    },
    macroItem: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      textAlign: 'left',
      gap: 0.25,
      px: 1.25,
      py: 1,
      borderRadius: 1,
      border: `1px solid transparent`,
      backgroundColor: 'transparent',
      color: fp.text.primary,
      cursor: 'pointer',
      '&:hover': { backgroundColor: fp.bg.hover },
    },
    macroItemActive: {
      borderColor: fp.accent,
      backgroundColor: fp.bg.active,
    },
    macroName: {
      fontSize: 13,
      fontWeight: 700,
      color: fp.text.primary,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    macroMeta: {
      fontSize: 11,
      color: fp.text.muted,
      lineHeight: 1.4,
    },
    editor: {
      minWidth: 0,
    },
    toolbar: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: 0.75,
      p: 1.25,
      borderBottom: `1px solid ${fp.divider}`,
      flexShrink: 0,
    },
    blockRail: {
      position: 'relative',
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      gap: 1,
      p: 1.5,
      minHeight: 0,
      overflowY: 'auto',
      '&::before': {
        content: '""',
        position: 'absolute',
        left: 55,
        top: 24,
        bottom: 24,
        width: 2,
        backgroundColor: fp.divider,
      },
    },
    block: {
      position: 'relative',
      display: 'grid',
      gridTemplateColumns: '24px 42px auto 1fr',
      alignItems: 'center',
      gap: 1,
      px: 1.25,
      py: 1,
      borderRadius: 1.25,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.elevated,
      color: fp.text.primary,
      cursor: 'pointer',
      zIndex: 1,
      '&:hover': { backgroundColor: fp.bg.hover },
    },
    blockDragging: {
      opacity: 0.4,
    },
    blockDragOver: {
      borderColor: fp.accent,
      boxShadow: `0 -2px 0 ${fp.accent}`,
    },
    blockIndex: {
      fontSize: 12,
      fontWeight: 700,
      color: fp.text.muted,
      textAlign: 'right',
      userSelect: 'none',
    },
    blockSelected: {
      borderColor: fp.accent,
      boxShadow: `0 0 0 1px ${fp.accent}`,
    },
    blockRunning: {
      borderColor: fp.status.success,
      backgroundColor: fp.bg.active,
    },
    blockIcon: {
      width: 30,
      height: 30,
      borderRadius: 1,
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: fp.bg.surface,
      color: fp.accent,
      cursor: 'grab',
      '&:active': { cursor: 'grabbing' },
    },
    blockBadges: {
      display: 'flex',
      alignItems: 'center',
      gap: 0.5,
      minWidth: 0,
    },
    blockBadge: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      px: 0.75,
      minWidth: 24,
      height: 24,
      borderRadius: 1,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.surface,
      color: fp.text.secondary,
      fontSize: 12,
      fontWeight: 700,
      lineHeight: 1,
      whiteSpace: 'nowrap',
      maxWidth: 120,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    blockBadgeEditable: {
      cursor: 'text',
      '&:hover': { borderColor: fp.accent, color: fp.text.primary },
    },
    blockBadgeInput: {
      width: 56,
      maxWidth: 56,
      boxSizing: 'border-box',
      textAlign: 'center',
      outline: 'none',
      borderColor: fp.accent,
      backgroundColor: fp.bg.elevated,
      color: fp.text.primary,
      fontFamily: 'inherit',
      // Hide the number spinner so the chip keeps its compact look.
      '&::-webkit-outer-spin-button': { WebkitAppearance: 'none', margin: 0 },
      '&::-webkit-inner-spin-button': { WebkitAppearance: 'none', margin: 0 },
    },
    blockTitle: {
      // Anchored to the whole block's horizontal centre (not the grid cell) so
      // the label lines up across every row regardless of badge width.
      position: 'absolute',
      left: '50%',
      transform: 'translateX(-50%)',
      fontSize: 13,
      fontWeight: 700,
      color: fp.text.primary,
      textAlign: 'center',
      pointerEvents: 'none',
      whiteSpace: 'nowrap',
    },
    blockActions: {
      display: 'flex',
      gap: 0.25,
      justifySelf: 'end',
    },
    sideForm: {
      display: 'flex',
      flexDirection: 'column',
      gap: 1.25,
      p: 1.5,
      minHeight: 0,
      overflowY: 'auto',
    },
    field: {
      display: 'flex',
      flexDirection: 'column',
      gap: 0.5,
    },
    label: {
      fontSize: 11,
      fontWeight: 700,
      color: fp.text.muted,
      textTransform: 'uppercase',
      letterSpacing: 0.04,
    },
    input: {
      width: '100%',
      boxSizing: 'border-box',
      px: 1,
      py: 0.75,
      borderRadius: 1,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.elevated,
      color: fp.text.primary,
      fontSize: 13,
      outline: 'none',
      '&:focus': { borderColor: fp.accent },
    },
    textarea: {
      minHeight: 72,
      resize: 'vertical',
      fontFamily: 'inherit',
    },
    button: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 0.5,
      px: 1.1,
      py: 0.7,
      borderRadius: 1,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.elevated,
      color: fp.text.primary,
      fontSize: 12,
      fontWeight: 700,
      cursor: 'pointer',
      '&:hover': { backgroundColor: fp.bg.hover },
      '&:disabled': { opacity: 0.55, cursor: 'not-allowed' },
    },
    primaryButton: {
      borderColor: fp.accent,
      color: fp.accent,
      backgroundColor: fp.bg.active,
    },
    dangerButton: {
      borderColor: fp.status.danger,
      color: fp.status.danger,
    },
    status: {
      fontSize: 12,
      color: fp.text.muted,
      lineHeight: 1.5,
      px: 1.5,
      pb: 1.5,
      flexShrink: 0,
    },
    captureDelaysToggle: {
      display: 'flex',
      alignItems: 'center',
      gap: 0.5,
      ml: 'auto',
    },
    captureDelaysLabel: {
      fontSize: 12,
      color: fp.text.secondary,
      lineHeight: 1.4,
    },
    errorText: {
      fontSize: 12,
      color: fp.status.danger,
      lineHeight: 1.5,
    },
    statusOk: {
      fontSize: 11,
      color: fp.status.success,
      lineHeight: 1.5,
    },
    statusMuted: {
      fontSize: 11,
      color: fp.status.warning,
      lineHeight: 1.5,
    },
    hintText: {
      fontSize: 11,
      color: fp.status.warning,
      lineHeight: 1.5,
    },
    empty: {
      p: 3,
      textAlign: 'center',
      color: fp.text.muted,
      fontSize: 13,
    },
  };
};
