import type { SxProps, Theme } from '@mui/material';

export const pianoRollViewStyles = (theme: Theme): Record<string, SxProps<Theme>> => {
  const fp = theme.palette.foundation;
  return {
    root: {
      p: 2,
      borderRadius: 1.5,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.content,
      display: 'flex',
      flexDirection: 'column',
      gap: 1.5,
      minWidth: 0,
    },
    header: {
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 2,
      flexWrap: 'wrap',
    },
    titleBlock: {
      display: 'flex',
      flexDirection: 'column',
      gap: 0.5,
    },
    eyebrow: {
      fontSize: 11,
      fontWeight: 700,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      color: fp.accent,
    },
    title: {
      color: fp.text.primary,
      fontSize: 16,
      fontWeight: 800,
    },
    meta: {
      color: fp.text.muted,
      fontSize: 12,
      lineHeight: 1.5,
    },
    stats: {
      display: 'flex',
      gap: 0.75,
      flexWrap: 'wrap',
      justifyContent: { xs: 'flex-start', md: 'flex-end' },
    },
    statChip: {
      px: 1,
      py: 0.4,
      borderRadius: 1,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.elevated,
      color: fp.text.secondary,
      fontSize: 12,
      fontVariantNumeric: 'tabular-nums',
    },
    viewport: {
      borderRadius: 1.5,
      border: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.elevated,
      overflowX: 'auto',
      overflowY: 'hidden',
    },
    timeline: {
      minWidth: 760,
      display: 'grid',
      gridTemplateColumns: '52px minmax(680px, 1fr)',
      gridTemplateRows: '28px 432px',
    },
    tickSpacer: {
      borderRight: `1px solid ${fp.divider}`,
      borderBottom: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.content,
    },
    tickLayer: {
      position: 'relative',
      borderBottom: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.content,
    },
    tick: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      width: 1,
      backgroundColor: fp.divider,
      color: fp.text.muted,
      fontSize: 10,
      fontVariantNumeric: 'tabular-nums',
      '& span': {
        position: 'absolute',
        top: 6,
        left: 6,
        whiteSpace: 'nowrap',
      },
    },
    laneLabels: {
      display: 'grid',
      gridTemplateRows: 'repeat(36, 12px)',
      borderRight: `1px solid ${fp.divider}`,
      backgroundColor: fp.bg.content,
    },
    laneLabel: {
      px: 0.75,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottom: `1px solid ${fp.divider}`,
      color: fp.text.muted,
      fontSize: 9,
      fontVariantNumeric: 'tabular-nums',
      '&[data-active="true"]': {
        color: fp.text.primary,
        backgroundColor: fp.bg.hover,
      },
    },
    laneCanvas: {
      position: 'relative',
      height: 432,
      overflow: 'hidden',
      background: `repeating-linear-gradient(to bottom, ${fp.bg.content} 0, ${fp.bg.content} 11px, ${fp.divider} 11px, ${fp.divider} 12px)`,
    },
    note: {
      position: 'absolute',
      height: 9,
      minWidth: 3,
      borderRadius: 0.75,
      backgroundColor: fp.accent,
      border: `1px solid ${fp.accentHover}`,
      color: fp.bg.content,
      opacity: 0.84,
      overflow: 'hidden',
      whiteSpace: 'nowrap',
      textOverflow: 'clip',
      fontSize: 8,
      lineHeight: '9px',
      px: 0.3,
      transform: 'translateY(1px)',
      boxShadow: `0 0 0 1px ${fp.bg.content}`,
    },
    cursor: {
      position: 'absolute',
      top: 0,
      bottom: 0,
      width: 2,
      backgroundColor: fp.status.warning,
      boxShadow: `0 0 0 1px ${fp.bg.content}`,
      pointerEvents: 'none',
    },
    empty: {
      p: 2,
      borderRadius: 1.5,
      border: `1px dashed ${fp.divider}`,
      color: fp.text.muted,
      textAlign: 'center',
      backgroundColor: fp.bg.content,
    },
    warning: {
      color: fp.status.warning,
      fontSize: 12,
    },
  };
};
